export type CivicCategory = 'Roads' | 'Sanitation' | 'Utilities' | 'Safety' | 'Environment';
export type IssueStatus = 'Reported' | 'Assigned' | 'In Progress' | 'Resolved';
export type SeverityLevel = 'Low' | 'Medium' | 'High' | 'Critical';

export interface CivicComment {
  id: string;
  user: string;
  userEmail: string;
  text: string;
  createdAt: string;
}

export interface TimelineEvent {
  status: IssueStatus;
  description: string;
  timestamp: string;
  actor: 'Civic AI' | 'Municipal Worker' | 'System';
}

export interface AgentOutput {
  agentName: string;
  responsibility: string;
  status: 'idle' | 'running' | 'success' | 'failed';
  executionTimeMs: number;
  confidenceScore: number;
  thoughtProcess: string[];
  findings: any;
}

export interface ReplayStep {
  timestamp: string;
  agentName: string;
  message: string;
  type: 'log' | 'thought' | 'action' | 'finding' | 'error';
  data?: any;
}

export interface MultiAgentInvestigation {
  id: string;
  issueId: string;
  createdAt: string;
  orchestratorSummary: string;
  rootCauseAnalysis: string;
  severityScore: number; // 1 to 10
  confidencePercentage: number;
  duplicateDetectionResult: string;
  communityImpact: string;
  recommendedActionPlan: string[];
  followUpSuggestions: string[];
  agents: {
    forecast?: AgentOutput;
    vision: AgentOutput;
    location?: AgentOutput;
    geo: AgentOutput;
    cluster?: AgentOutput;
    risk: AgentOutput;
    impact?: AgentOutput;
    response?: AgentOutput;
    resolution: AgentOutput;
    coordinator?: AgentOutput;
    commander: AgentOutput;
  };
  replaySteps: ReplayStep[];
}

export interface CivicIssue {
  id: string;
  title: string;
  description: string;
  category: CivicCategory;
  status: IssueStatus;
  severity: SeverityLevel;
  communityImpact: string; // Dynamic community impact statement generated by AI
  duplicateGroupId?: string; // Set if AI detects this is a duplicate of another report
  location: {
    lat: number;
    lng: number;
    address: string;
    placeId?: string;
    geohash?: string;
  };
  reporter: {
    name: string;
    email: string;
    avatar?: string;
  };
  createdAt: string;
  updatedAt: string;
  imageUrl?: string;
  recommendedActions: string[]; // AI recommended steps
  upvotes: number;
  upvotedBy: string[]; // List of user emails who upvoted
  comments: CivicComment[];
  timeline: TimelineEvent[];
  investigation?: MultiAgentInvestigation;
}

export interface CommunityHealthStats {
  score: number;
  grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'F';
  analysis: string; // Text summary from AI
  totalActive: number;
  totalResolved: number;
  resolvedPercentage: number;
  averageResolutionDays: number;
  byCategory: Record<CivicCategory, number>;
  bySeverity: Record<SeverityLevel, number>;
}

export interface CivicBotMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  createdAt: string;
}

export interface CivicUser {
  name: string;
  email: string;
  points: number;
  reportsCount: number;
  resolvedCount: number;
}

